version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      freshness: # default freshness
        warn_after: {count: 12, period: hour}
        error_after: {count: 24, period: hour}
      loaded_at_field: time_val
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
            tests:
              - not_empty
